In [61]:
import pandas as pd

In [62]:
data=pd.read_csv('data/transport_bus_passager_par_route.csv',sep=';')

In [63]:
data

,Route,1999/00,2000/01,2001/02,2002/03,2003/04,2004/05,2005/06,2006/07,2007/08,2008/09,2009/10,2010/11,2011/12,2012/13
0,25,10085060,11348007,12320822,14302139,17119099,21057007,22053873,22368234,22830950,23128928,23170101,23301504,23000069,23415401
1,18,8383642,9828572,10628128,12529260,14100375,15623555,15934531,16161666,16495991,16711288,16741037,16874721,17686579,17153879
2,29,10547611,11575323,12324516,13344498,15661574,16991637,16880308,14328922,14625335,14816217,14842592,14926768,15702341,16873388
3,149,12035990,12921115,13725659,14249299,15792034,15211949,14855799,15067557,15379249,15579971,15607706,15320187,14883534,14612975
4,38,9593947,9593238,9049692,10460021,12299236,10968691,13970156,17860498,18229966,18467894,17469872,15253720,14858555,13503949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,TL1,191210,31155,0,0,0,0,0,0,0,0,0,0,0,0
1010,W13D,14170,32790,29662,30167,27390,22940,5623,17412,0,0,0,0,0,0
1011,W17,70625,0,0,0,0,0,0,0,0,0,0,0,0,0
1012,X30,112119,12396,0,0,0,0,0,0,0,0,0,0,0,0
1013,X53,187275,0,0,0,0,0,0,0,0,0,0,0,0,0

In [64]:
df = pd.DataFrame(data)

In [65]:
df

,Route,1999/00,2000/01,2001/02,2002/03,2003/04,2004/05,2005/06,2006/07,2007/08,2008/09,2009/10,2010/11,2011/12,2012/13
0,25,10085060,11348007,12320822,14302139,17119099,21057007,22053873,22368234,22830950,23128928,23170101,23301504,23000069,23415401
1,18,8383642,9828572,10628128,12529260,14100375,15623555,15934531,16161666,16495991,16711288,16741037,16874721,17686579,17153879
2,29,10547611,11575323,12324516,13344498,15661574,16991637,16880308,14328922,14625335,14816217,14842592,14926768,15702341,16873388
3,149,12035990,12921115,13725659,14249299,15792034,15211949,14855799,15067557,15379249,15579971,15607706,15320187,14883534,14612975
4,38,9593947,9593238,9049692,10460021,12299236,10968691,13970156,17860498,18229966,18467894,17469872,15253720,14858555,13503949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,TL1,191210,31155,0,0,0,0,0,0,0,0,0,0,0,0
1010,W13D,14170,32790,29662,30167,27390,22940,5623,17412,0,0,0,0,0,0
1011,W17,70625,0,0,0,0,0,0,0,0,0,0,0,0,0
1012,X30,112119,12396,0,0,0,0,0,0,0,0,0,0,0,0
1013,X53,187275,0,0,0,0,0,0,0,0,0,0,0,0,0

In [66]:
df_melted = df.melt(id_vars=["Route"], var_name="AnnÃ©e", value_name="Valeur")

In [67]:
df_melted

      Route    AnnÃ©e    Valeur
0        25  1999/00  10085060
1        18  1999/00   8383642
2        29  1999/00  10547611
3       149  1999/00  12035990
4        38  1999/00   9593947
...     ...      ...       ...
14191   TL1  2012/13         0
14192  W13D  2012/13         0
14193   W17  2012/13         0
14194   X30  2012/13         0
14195   X53  2012/13         0

[14196 rows x 3 columns]

In [68]:
df_melted["Valeur"] = df_melted["Valeur"].astype(str)  # Convertir en chaÃ®nes de caractÃ¨res
df_melted["Valeur"] = df_melted["Valeur"].str.replace(" ", "")  # Retirer les espaces
df_melted["Valeur"] = pd.to_numeric(df_melted["Valeur"], errors='coerce')  # Convertir en int

In [69]:
print(df_melted["Valeur"].dtype)

int64

In [77]:
import pandas as pd
import plotly.graph_objects as go
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
from fbprophet import Prophet

# ==============================
# ðŸ”¹ Ã‰tape 1 : Chargement des donnÃ©es
# ==============================
data = pd.read_csv('data/transport_bus_passager_par_route.csv', sep=';')

# Transformation du DataFrame pour Prophet
df_melted = pd.melt(data, id_vars='Route', var_name='AnnÃ©e', value_name='Valeur')

# Extraction de l'annÃ©e (ex: "1999/00" â†’ "1999")
df_melted['AnnÃ©e'] = df_melted['AnnÃ©e'].str[:4]
df_melted['AnnÃ©e'] = pd.to_datetime(df_melted['AnnÃ©e'], format='%Y')

# Tri des donnÃ©es
df_melted = df_melted.sort_values(by=['Route', 'AnnÃ©e']).reset_index(drop=True)

# ==============================
# ðŸ”¹ Ã‰tape 2 : Fonction de prÃ©diction
# ==============================
def predict_route(selected_route):
    df_filtered = df_melted[df_melted["Route"] == selected_route]

    # CrÃ©ation du DataFrame pour Prophet
    df_prophet = df_filtered[['AnnÃ©e', 'Valeur']].rename(columns={'AnnÃ©e': 'ds', 'Valeur': 'y'})

    # Initialisation et entraÃ®nement de Prophet
    model = Prophet(interval_width=0.95)
    model.fit(df_prophet)

    # CrÃ©ation du DataFrame pour les prÃ©visions (jusqu'en 2024)
    future = model.make_future_dataframe(periods=11, freq='Y')  # 11 ans aprÃ¨s 2013
    forecast = model.predict(future)

    return df_prophet, forecast

# ==============================
# ðŸ”¹ Ã‰tape 3 : Application Dash
# ==============================
app = dash.Dash(__name__)

# Layout de l'application
app.layout = html.Div([
    html.Label("SÃ©lectionnez une Route :"),
    dcc.Dropdown(
        id='route-dropdown',
        options=[{'label': f"Route {route}", 'value': route} for route in df_melted["Route"].unique()],
        value=df_melted["Route"].unique()[0],  # Route sÃ©lectionnÃ©e par dÃ©faut
        style={'width': '50%'}
    ),
    dcc.Graph(id='evolution-graph')
])

# Callback pour mettre Ã  jour le graphique
@app.callback(
    Output('evolution-graph', 'figure'),
    [Input('route-dropdown', 'value')]
)
def update_graph(selected_route):
    df_prophet, forecast = predict_route(selected_route)

    fig = go.Figure()

    # ðŸ”¹ Ajout des donnÃ©es historiques
    fig.add_trace(go.Scatter(
        x=df_prophet["ds"],
        y=df_prophet["y"],
        mode='lines+markers',
        name=f"ObservÃ© - Route {selected_route}",
        hovertemplate='%{y} vÃ©hicules<br>AnnÃ©e: %{x|%Y}<extra></extra>',
    ))

    # ðŸ”¹ Ajout des prÃ©visions
    fig.add_trace(go.Scatter(
        x=forecast["ds"],
        y=forecast["yhat"],
        mode='lines',
        name=f"PrÃ©diction - Route {selected_route}",
        line=dict(dash='dash', color='red'),
        hovertemplate='%{y:.0f} vÃ©hicules<br>AnnÃ©e: %{x|%Y}<extra></extra>',
    ))

    # ðŸ”¹ Ajout de l'incertitude
    fig.add_trace(go.Scatter(
        x=forecast["ds"].tolist() + forecast["ds"][::-1].tolist(),
        y=forecast["yhat_upper"].tolist() + forecast["yhat_lower"][::-1].tolist(),
        fill='toself',
        fillcolor='rgba(255, 0, 0, 0.2)',
        line=dict(color='rgba(255,255,255,0)'),
        hoverinfo="skip",
        showlegend=True,
        name="Incertitude",
    ))

    # ðŸ”¹ Mise en forme du graphique
    fig.update_layout(
        title=f'Ã‰volution et PrÃ©diction du trafic pour la Route {selected_route}',
        xaxis_title='AnnÃ©e',
        yaxis_title='Nombre de vÃ©hicules',
        hovermode='x unified',
        template='plotly_dark',
    )

    return fig

# ==============================
# ðŸ”¹ Ã‰tape 4 : Lancement de l'application
# ==============================
if __name__ == '__main__':
    app.run_server(debug=True)

ModuleNotFoundError: No module named 'fbprophet'

In [ ]:
# Importation des bibliothÃ¨ques nÃ©cessaires
import pandas as pd
import plotly.graph_objects as go
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
from prophet import Prophet

# Lecture du fichier CSV
data = pd.read_csv('data/transport_bus_passager_par_route.csv', sep=';')

# Transformation du DataFrame pour Prophet
df_melted = pd.melt(data, 
                    id_vars='Route', 
                    var_name='AnnÃ©e', 
                    value_name='Valeur')

# Conversion du format de l'annÃ©e
df_melted['AnnÃ©e'] = df_melted['AnnÃ©e'].str[:4]  # Garde juste le dÃ©but de l'annÃ©e (ex: 1999)
df_melted['AnnÃ©e'] = pd.to_datetime(df_melted['AnnÃ©e'], format='%Y')
df_melted = df_melted.sort_values(by=['Route', 'AnnÃ©e']).reset_index(drop=True)

# Fonction de prÃ©paration des donnÃ©es pour Prophet
def prepare_data_for_prophet(selected_route):
    df_filtered = df_melted[df_melted["Route"] == selected_route]
    df_prophet = df_filtered[["AnnÃ©e", "Valeur"]].rename(columns={"AnnÃ©e": "ds", "Valeur": "y"})
    return df_prophet

# Fonction de prÃ©diction avec Prophet
def predict_route(selected_route):
    # PrÃ©paration des donnÃ©es
    df_prophet = prepare_data_for_prophet(selected_route)

    # Initialisation de Prophet
    model = Prophet(interval_width=0.95)
    model.fit(df_prophet)

    # GÃ©nÃ©ration des dates futures jusqu'Ã  2024
    future_dates = model.make_future_dataframe(periods=12, freq='Y')
    forecast = model.predict(future_dates)

    return df_prophet, forecast

# Initialisation de l'application Dash
app = dash.Dash(__name__)

# Layout de l'application Dash
app.layout = html.Div([
    html.Label("SÃ©lectionnez une Route :"),
    dcc.Dropdown(
        id='route-dropdown',
        options=[{'label': f"Route {route}", 'value': route} for route in df_melted["Route"].unique()],
        value=df_melted["Route"].unique()[0],  # Route sÃ©lectionnÃ©e par dÃ©faut
        style={'width': '50%'}
    ),

    dcc.Graph(id='evolution-graph')
])

# Callback pour mettre Ã  jour le graphique en fonction de la route sÃ©lectionnÃ©e
@app.callback(
    Output('evolution-graph', 'figure'),
    [Input('route-dropdown', 'value')]
)
def update_graph(selected_route):
    df_prophet, forecast = predict_route(selected_route)

    fig = go.Figure()

    # Tracer les donnÃ©es observÃ©es
    fig.add_trace(go.Scatter(
        x=df_prophet["ds"],
        y=df_prophet["y"],
        mode='lines+markers',
        name=f"ObservÃ© - Route {selected_route}",
        hovertemplate='%{y} vÃ©hicules<br>AnnÃ©e: %{x|%Y}<extra></extra>',
    ))

    # Tracer les prÃ©dictions
    fig.add_trace(go.Scatter(
        x=forecast["ds"],
        y=forecast["yhat"],
        mode='lines',
        name=f"PrÃ©diction - Route {selected_route}",
        line=dict(dash='dash', color='red'),
        hovertemplate='%{y:.0f} vÃ©hicules<br>AnnÃ©e: %{x|%Y}<extra></extra>',
    ))

    # Ajouter l'incertitude (intervalle de confiance)
    fig.add_trace(go.Scatter(
        x=forecast["ds"].tolist() + forecast["ds"][::-1].tolist(),
        y=forecast["yhat_upper"].tolist() + forecast["yhat_lower"][::-1].tolist(),
        fill='toself',
        fillcolor='rgba(255, 0, 0, 0.2)',
        line=dict(color='rgba(255,255,255,0)'),
        hoverinfo="skip",
        showlegend=True,
        name="Incertitude",
    ))

    # Mise en page du graphique
    fig.update_layout(
        title=f'Ã‰volution et PrÃ©diction du trafic pour la Route {selected_route}',
        yaxis_title='Nombre de vÃ©hicules',
        hovermode='x unified',
        template='plotly_dark',
    )

    return fig

# Lancer l'application
if __name__ == '__main__':
    app.run_server(debug=True)

  Route      AnnÃ©e   Valeur
0     1 1999-01-01  3397278
1     1 2000-01-01  3730801
2     1 2001-01-01  3920526
3     1 2002-01-01  4273487
4     1 2003-01-01  5231558

17:37:05 - cmdstanpy - INFO - Chain [1] start processing
17:37:05 - cmdstanpy - INFO - Chain [1] done processing
17:37:05 - cmdstanpy - INFO - Chain [1] start processing
17:37:05 - cmdstanpy - INFO - Chain [1] done processing
17:37:12 - cmdstanpy - INFO - Chain [1] start processing
17:37:12 - cmdstanpy - INFO - Chain [1] done processing
17:37:16 - cmdstanpy - INFO - Chain [1] start processing
17:37:16 - cmdstanpy - INFO - Chain [1] done processing
17:37:19 - cmdstanpy - INFO - Chain [1] start processing
17:37:19 - cmdstanpy - INFO - Chain [1] done processing
17:37:22 - cmdstanpy - INFO - Chain [1] start processing
17:37:22 - cmdstanpy - INFO - Chain [1] done processing

In [60]:
import pandas as pd
import plotly.graph_objects as go
import dash
from dash import dcc, html
from dash.dependencies import Input, Output

# Initialisation de l'application Dash
app = dash.Dash(__name__)

# Layout de l'application Dash
app.layout = html.Div([
    html.Label("SÃ©lectionnez une Route :"),
    dcc.Dropdown(
        id='route-dropdown',
        options=[{'label': f"Route {route}", 'value': route} for route in df["Route"].unique()],
        value=df["Route"].unique()[0],  # Route sÃ©lectionnÃ©e par dÃ©faut
        style={'width': '50%'}
    ),

    dcc.Graph(id='evolution-graph')
])

# Callback pour mettre Ã  jour le graphique en fonction de la route sÃ©lectionnÃ©e
@app.callback(
    Output('evolution-graph', 'figure'),
    [Input('route-dropdown', 'value')]
)
def update_graph(selected_route):
    df_filtered = df_melted[df_melted["Route"] == selected_route]

    fig = go.Figure()

    # Tracer la courbe pour la route sÃ©lectionnÃ©e
    fig.add_trace(go.Scatter(
        x=df_filtered["AnnÃ©e"],
        y=df_filtered["Valeur"],
        mode='lines+markers',
        name=f"Route {selected_route}",
        hovertemplate='%{y} vÃ©hicules<br>AnnÃ©e: %{x}<extra></extra>',
    ))

    # Mise Ã  jour dynamique de l'Ã©chelle de l'axe y en fonction des valeurs de la route
    fig.update_layout(
        title=f'Ã‰volution du trafic pour la Route {selected_route}',
        xaxis_title='AnnÃ©e',
        yaxis_title='Nombre de vÃ©hicules',
        yaxis=dict(
            range=[df_filtered["Valeur"].min() * 0.95, df_filtered["Valeur"].max() * 1.05],  # Ajuste l'Ã©chelle selon les valeurs
        ),
        hovermode='x unified',
        template='plotly_dark',
    )

    return fig

# Lancer l'application
if __name__ == '__main__':
    app.run_server(debug=True)